apiVersion: v1
kind: Pod
metadata:
  name: affinity
spec:
  containers:
    - name: container
      image: centos:7
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'sleep 7000']
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: hello
                operator: In
                values:
                  - hi
