apiVersion: v1
kind: Pod
metadata:
  name: nginx-cm
spec:
  containers:
    - name: nginx-cm
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: test

  volumes:
    - name: test
      configMap:
        name: nginx-cm
        items:
         - key: nginx-custom.conf
           path: default.conf
