apiVersion: v1
kind: Pod
metadata:
  name: cm-var
spec:
  containers:
     - name: mycont
       image: nginx
       imagePullPolicy: IfNotPresent
       env:
         - name: myvar
           valueFrom:
             configMapKeyRef:
               name: myconfig
               key: COLOR
