apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate
  labels:
    app: my-nginx
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      name: Rolling-Update
      labels:
        app: my-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.9

