apiVersion: v1
kind: Pod
metadata:
  name: lab9
spec:
  containers:
    - name: container
      image: nginx
      imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disk
            operator: In
            values:
            - ssd
