apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-07-08T10:40:29Z"
  labels:
    app: mydb
  name: mydb
  namespace: default
  resourceVersion: "633054"
  uid: 53550d84-7f17-4de9-804a-19b2b1cf2cc7
spec:
  ports:
  - port: 9377
    protocol: TCP
    targetPort: 80
  selector:
    app: myservice
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
