apiVersion: v1
kind: Pod
metadata:
  name: mysql-wp
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: "redhat"
        - name: "MYSQL_DATABASE"
          value: "mayank"

