apiVersion: v1
kind: Pod
metadata:
  name: resource-limitpod
spec:
  containers:
    - name: httpd
      image: centos/httpd
      resources:
        limits:
          cpu: "500m"
          memory: "1500Mi"
        requests:
          cpu: "300m"
          memory: "400Mi"
