apiVersion: v1
kind: Pod
metadata:
  name: net-pod
spec:
  containers:
    - name: busy1
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "3600"

    - name: busy2
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - "sleep"
        - "3600"
