apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  accessModes: 
    - ReadWriteMany
  nfs:
    path: /data
    server: dell-per620-3.gsslab.rdu2.redhat.com
    readOnly: false
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 5Gi

