apiVersion: v1
kind: Pod
metadata:
   name: mypod1
   namespace: default
spec:
   containers:
     - name: busybox
       image: busybox
       command:
        - sleep
        - "300"
     - name: nginx
       image: nginx
