apiVersion: v1
kind: PersistentVolume
metadata:
 name: my-pv
spec:
  accessModes:
    - ReadWriteMany
  hostPath: 
    path: /home/
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 3Gi
