apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-sc
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 3Gi
  storageClassName: nfs
  nfs:
    server: kvm-02-guest16.lab.eng.rdu2.redhat.com
    path: /srv/nfs/kubedata/
