apiVersion: v1
kind: Pod
metadata:
  name: sched
spec:
  containers:
    - name: container
      image: centos:7
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', 'sleep 7000']
  nodeSelector:
    disktype: ssd
