apiVersion: v1
kind: Pod
metadata:
  name: secret
spec:
  containers:
     - name: mycont
       image: busybox
       command:
         - sleep
         - "3600"
       imagePullPolicy: IfNotPresent
       volumeMounts:
         - name: secret
           mountPath: /var/

  volumes:
    - name: secret
      secret:
        secretName: secretstuff
