kind: Pod
apiVersion: v1
metadata:
  name: sidecar-pod
spec:
  volumes:
    - name: logs
      emptyDir: {}
  containers:
    - name: app1
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo 'hello mayank' >> /var/log/name.txt; sleep 2; date >> /var/log/name.txt; done"]
      volumeMounts:
      -  name: logs
         mountPath: /var/log

    - name: sidecar1
      image: centos/httpd
      ports:
      - containerPort: 80
      volumeMounts:
      - name: logs
        mountPath: /var/www/html

