apiVersion: v1
kind: Pod
metadata:
  name: hostvolume
spec:
  containers:
     - name: mycont
       image: httpd
       imagePullPolicy: IfNotPresent
       volumeMounts:
         - name: httpd
           mountPath: /var/www
  volumes:
    - name: httpd
      persistentVolumeClaim:
        claimName: hostvolume  
